// src/pages/Platform.jsx
import { motion as Motion } from "framer-motion";
import { useOutletContext } from "react-router-dom";
import {
  Sparkles,
  FileSearch,
  Play,
  Users,
  PenTool,
  Brain,
  BarChart3,
  Shield,
  ArrowRight,
  CheckCircle,
} from "lucide-react";

const steps = [
  {
    num: "01",
    title: "Write Scenarios",
    desc: "Describe what you want to test using BDD/Gherkin syntax — plain language anyone can understand.",
    icon: PenTool,
  },
  {
    num: "02",
    title: "AI Generates Code",
    desc: "The AI transforms your scenarios into production-ready Playwright test code instantly.",
    icon: Brain,
  },
  {
    num: "03",
    title: "Execute Tests",
    desc: "Run your tests with one click — headed or headless, single or batch. See results in real time.",
    icon: Play,
  },
  {
    num: "04",
    title: "Analyze & Improve",
    desc: "View detailed results, video recordings, step-by-step logs. AI suggests fixes for failures.",
    icon: BarChart3,
  },
];

const features = [
  {
    icon: Sparkles,
    title: "AI-Powered Test Generation",
    desc: "Write scenarios in Gherkin and get executable Playwright code generated by AI. Supports project-specific context, selectors, and parameters for highly accurate tests.",
    color: "sky",
  },
  {
    icon: FileSearch,
    title: "Document Analysis",
    desc: "Upload PDF, Word, or Markdown files. AI extracts test scenarios and user stories from your requirements documents automatically.",
    color: "violet",
  },
  {
    icon: Play,
    title: "Test Execution & Reporting",
    desc: "Run tests individually or in batches. Get real-time results, video recordings, step-by-step logs, and detailed pass/fail analytics.",
    color: "emerald",
  },
  {
    icon: Brain,
    title: "Self-Healing Tests",
    desc: "When a test fails, AI analyzes the error and proposes a fix. Review, accept, and move on — no manual debugging needed.",
    color: "amber",
  },
  {
    icon: Users,
    title: "Team Collaboration",
    desc: "Multi-project workspaces, team management, folders, role-based access. Everyone works in the same environment.",
    color: "sky",
  },
  {
    icon: Shield,
    title: "Bring Your Own AI",
    desc: "Configure your preferred AI provider per project — OpenAI, Azure, or custom endpoints. Your API keys stay encrypted.",
    color: "violet",
  },
];

const audiences = [
  { label: "QA Engineers", desc: "Accelerate test creation and reduce maintenance overhead." },
  { label: "Business Analysts", desc: "Write test scenarios in plain language — no coding required." },
  { label: "Product Owners", desc: "Ensure acceptance criteria are automatically verified." },
  { label: "Development Teams", desc: "Integrate AI-generated tests into your CI/CD pipeline." },
];

const colorMap = {
  sky: "bg-sky-100 text-sky-600",
  violet: "bg-violet-100 text-violet-600",
  emerald: "bg-emerald-100 text-emerald-600",
  amber: "bg-amber-100 text-amber-600",
};

export default function Platform() {
  const { onBook } = useOutletContext();

  return (
    <>
      {/* ── Hero ──────────────────────────────────────────── */}
      <section className="relative overflow-hidden py-20 md:py-28">
        <div className="hero-glow-light -z-10" aria-hidden />
        <div className="mx-auto max-w-6xl px-6 text-center">
          <Motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <span className="inline-block rounded-full bg-sky-100 px-4 py-1.5 text-xs font-semibold uppercase tracking-wider text-sky-700 mb-5">
              TestHive Platform
            </span>
            <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight text-slate-900">
              AI-powered test automation
              <br className="hidden sm:block" />
              <span className="text-sky-500">for everyone</span>
            </h1>
            <p className="mt-5 max-w-2xl mx-auto text-lg md:text-xl text-slate-600">
              Turn requirements into executable tests without writing code.
              Write what you want to test, let AI generate the code, execute with one click,
              and get results — all in one platform.
            </p>
            <div className="mt-8 flex items-center justify-center gap-4 flex-wrap">
              <a
                href="https://aithentic.testhive.ma"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-sky-400 via-emerald-400 to-violet-500 px-6 py-3 text-base font-semibold text-white shadow-md hover:brightness-110 active:scale-95 transition"
              >
                Try the Platform <ArrowRight className="h-4 w-4" />
              </a>
              <button
                onClick={onBook}
                className="inline-flex items-center rounded-xl border border-slate-200 bg-white px-6 py-3 text-base font-semibold text-slate-700 shadow-sm hover:bg-slate-50 transition"
              >
                Request a Demo
              </button>
            </div>
          </Motion.div>
        </div>
      </section>

      {/* ── How it works ──────────────────────────────────── */}
      <section className="py-20 bg-slate-50 border-y border-slate-100">
        <div className="mx-auto max-w-6xl px-6">
          <Motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-14"
          >
            <h2 className="text-3xl md:text-4xl font-extrabold text-slate-900">
              How it <span className="text-sky-500">works</span>
            </h2>
            <p className="mt-3 text-lg text-slate-600">Four steps from idea to verified test results.</p>
          </Motion.div>

          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {steps.map((s, i) => (
              <Motion.div
                key={s.num}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.45, delay: i * 0.1 }}
                className="relative rounded-xl border border-slate-200 bg-white p-6 shadow-sm"
              >
                <span className="text-4xl font-extrabold text-sky-100">{s.num}</span>
                <div className="mt-2 mb-3">
                  <s.icon className="h-6 w-6 text-sky-500" />
                </div>
                <h3 className="text-lg font-semibold text-slate-900 mb-2">{s.title}</h3>
                <p className="text-sm text-slate-600 leading-relaxed">{s.desc}</p>
              </Motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ──────────────────────────────────────── */}
      <section className="py-20">
        <div className="mx-auto max-w-6xl px-6">
          <Motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-14"
          >
            <h2 className="text-3xl md:text-4xl font-extrabold text-slate-900">
              Everything you need to <span className="text-sky-500">test smarter</span>
            </h2>
          </Motion.div>

          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            {features.map((f, i) => (
              <Motion.div
                key={f.title}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.45, delay: i * 0.06 }}
                className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm hover:shadow-lg transition-shadow"
              >
                <div className={`inline-flex items-center justify-center w-10 h-10 rounded-lg ${colorMap[f.color]} mb-4`}>
                  <f.icon className="h-5 w-5" />
                </div>
                <h3 className="text-base font-semibold text-slate-900 mb-2">{f.title}</h3>
                <p className="text-sm text-slate-600 leading-relaxed">{f.desc}</p>
              </Motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Who is it for ─────────────────────────────────── */}
      <section className="py-20 bg-gradient-to-b from-white via-violet-50/40 to-white border-t border-slate-100">
        <div className="mx-auto max-w-4xl px-6">
          <Motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl md:text-4xl font-extrabold text-slate-900">
              Built for <span className="text-sky-500">your team</span>
            </h2>
            <p className="mt-3 text-lg text-slate-600">
              Whether you write code or not — TestHive Platform makes test automation accessible.
            </p>
          </Motion.div>

          <div className="grid gap-4 sm:grid-cols-2">
            {audiences.map((a, i) => (
              <Motion.div
                key={a.label}
                initial={{ opacity: 0, x: -16 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.08 }}
                className="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"
              >
                <CheckCircle className="h-5 w-5 text-emerald-500 mt-0.5 flex-shrink-0" />
                <div>
                  <h3 className="font-semibold text-slate-900">{a.label}</h3>
                  <p className="text-sm text-slate-600 mt-1">{a.desc}</p>
                </div>
              </Motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Bottom CTA ────────────────────────────────────── */}
      <section className="py-20 bg-gradient-to-r from-sky-50 via-white to-violet-50">
        <div className="mx-auto max-w-3xl px-6 text-center">
          <Motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
          >
            <h2 className="text-3xl md:text-4xl font-extrabold text-slate-900 mb-4">
              Start testing today
            </h2>
            <p className="text-lg text-slate-600 mb-8">
              Create your free account and generate your first AI-powered test in minutes.
            </p>
            <div className="flex items-center justify-center gap-4 flex-wrap">
              <a
                href="https://aithentic.testhive.ma"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-sky-400 via-emerald-400 to-violet-500 px-8 py-3 text-base font-semibold text-white shadow-md hover:brightness-110 active:scale-95 transition"
              >
                Get Started Free <ArrowRight className="h-4 w-4" />
              </a>
              <button
                onClick={onBook}
                className="inline-flex items-center rounded-xl border border-slate-200 bg-white px-8 py-3 text-base font-semibold text-slate-700 shadow-sm hover:bg-slate-50 transition"
              >
                Book a Demo
              </button>
            </div>
          </Motion.div>
        </div>
      </section>
    </>
  );
}
